#!/bin/bash

alias ramdisk-alfresco-create='sudo mount -t tmpfs -o size=2048M tmpfs /ramdisk/ && cp -R /opt/alfresco-4.2.c-for-ramdisk/alfresco-4.2.c /ramdisk/'
alias ramdisk-alfresco-start='(cd /ramdisk/alfresco-4.2.c/ && ./alfresco.sh start)'
alias ramdisk-alfresco-stop='(cd /ramdisk/alfresco-4.2.c/ && ./alfresco.sh stop)'
alias ramdisk-alfresco-delete='sudo umount /ramdisk'
